import { MigrationInterface, QueryRunner } from 'typeorm';

export class SeedCarBrands1781959064657 implements MigrationInterface {
  private readonly brands = [
    'Toyota',
    'Lexus',
    'Honda',
    'Acura',
    'Nissan',
    'Infiniti',
    'Mazda',
    'Subaru',
    'Mitsubishi',
    'Suzuki',
    'Daihatsu',
    'Isuzu',
    'BMW',
    'Mini',
    'Mercedes-Benz',
    'Smart',
    'Audi',
    'Volkswagen',
    'Porsche',
    'Opel',
    'Ferrari',
    'Lamborghini',
    'Maserati',
    'Alfa Romeo',
    'Fiat',
    'Abarth',
    'Lancia',
    'Peugeot',
    'Citroen',
    'DS Automobiles',
    'Renault',
    'Alpine',
    'Ford',
    'Chevrolet',
    'GMC',
    'Cadillac',
    'Chrysler',
    'Dodge',
    'Jeep',
    'Ram',
    'Lincoln',
    'Tesla',
    'Rivian',
    'Lucid',
    'Land Rover',
    'Range Rover',
    'Jaguar',
    'Bentley',
    'Rolls-Royce',
    'Aston Martin',
    'Lotus',
    'McLaren',
    'Volvo',
    'Polestar',
    'Koenigsegg',
    'Hyundai',
    'Kia',
    'Genesis',
    'SsangYong',
    'BYD',
    'Geely',
    'Zeekr',
    'Chery',
    'Exeed',
    'Jetour',
    'Haval',
    'Great Wall Motors',
    'Changan',
    'NIO',
    'XPeng',
    'Li Auto',
    'Hongqi',
    'FAW',
    'Dongfeng',
    'Tata Motors',
    'Mahindra',
    'Skoda',
    'SEAT',
    'Cupra',
    'Dacia',
    'Lada',
    'UAZ',
    'VinFast',
    'TOGG',
    'Pagani',
    'Bugatti',
    'Rimac',
    'Fisker',
    'Faraday Future',
    'Canoo',
    'Mitsubishi Fuso',
    'MAN',
    'Scania',
    'DAF',
    'Iveco',
    'Isuzu Trucks',
    'Hino',
    'KTM',
    'Polaris',
    'Roewe',
    'MG',
    'Maxus',
    'SAIC',
    'Baojun',
    'Wuling',
    'GAC',
    'JAC',
    'Seres',
    'Leapmotor',
    'Aion',
    'Avatr',
    'Maybach',
    'Alpina',
    'Brabus',
  ];

  public async up(queryRunner: QueryRunner): Promise<void> {
    const values = this.brands.map((_, i) => `($${i + 1})`).join(', ');
    await queryRunner.query(
      `INSERT INTO "car_brand" ("brand") VALUES ${values} ON CONFLICT ("brand") DO NOTHING`,
      this.brands,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const params = this.brands.map((_, i) => `$${i + 1}`).join(', ');
    await queryRunner.query(
      `DELETE FROM "car_brand" WHERE "brand" IN (${params})`,
      this.brands,
    );
  }
}
